server:
  port: 8090

spring:
  profiles:
    active: local
  sql:
    init:
      mode: always
  messages:
    fallback-to-system-locale: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.pixellink.model
  configuration:
    map-underscore-to-camel-case: true
